import { int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export type StrokeClinicalData = { cohort: "stroke"; strokeType: "ischemic" | "hemorrhagic" | "tia" | "other" | "unknown"; vascularTerritory: "anterior" | "posterior" | "multiple" | "unknown"; reperfusionTherapy: "none" | "iv_thrombolysis" | "mechanical_thrombectomy" | "both" | "unknown"; toastEtiology: "large_artery" | "cardioembolic" | "small_vessel" | "other_determined" | "undetermined" | "unknown" };
export type MultipleSclerosisClinicalData = { cohort: "multiple_sclerosis"; diseaseCourse: "relapsing_remitting" | "primary_progressive" | "secondary_progressive" | "clinically_isolated_syndrome" | "unknown"; disabilityLevel: "mild" | "moderate" | "severe" | "unknown"; relapseActivity: "active" | "inactive" | "unknown"; diseaseModifyingTherapy: "yes" | "no" | "unknown" };
export type AbnormalMovementClinicalData = { cohort: "abnormal_movements"; movementPhenotype: "tremor" | "dystonia" | "chorea" | "ataxia" | "tics" | "other" | "unknown"; distribution: "focal" | "segmental" | "generalized" | "unknown"; severity: "mild" | "moderate" | "severe" | "unknown"; functionalImpact: "none" | "mild" | "moderate" | "severe" | "unknown"; treatmentResponse: "responsive" | "partially_responsive" | "refractory" | "unknown" };
export type GuillainBarreClinicalData = { cohort: "guillain_barre"; variant: "aidp" | "aman" | "amsan" | "miller_fisher" | "other" | "unknown"; disabilityScore: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "unknown"; ventilatorySupport: "none" | "non_invasive" | "invasive" | "unknown"; treatment: "ivig" | "plasmapheresis" | "both" | "supportive" | "unknown" };
export type MyastheniaGravisClinicalData = { cohort: "myasthenia_gravis"; mgfaClass: "I" | "II" | "III" | "IV" | "V" | "unknown"; antibodyStatus: "achr" | "musk" | "lrp4" | "seronegative" | "unknown"; thymomaStatus: "present" | "absent" | "not_assessed" | "unknown"; crisisHistory: "never" | "past" | "current" | "unknown"; treatmentResponse: "responsive" | "partially_responsive" | "refractory" | "unknown" };
export type MyelopathyClinicalData = { cohort: "myelopathy"; level: "cervical" | "thoracic" | "lumbar" | "multilevel" | "unknown"; cause: "degenerative" | "inflammatory" | "compressive" | "vascular" | "infectious" | "other" | "unknown"; upperMotorNeuronSigns: "present" | "absent" | "unknown"; lowerMotorNeuronFeatures: "present" | "absent" | "unknown"; bladderInvolvement: "yes" | "no" | "unknown" };
export type NeuroOphthalmologyClinicalData = { cohort: "neuro_ophthalmology"; visualSyndrome: "optic_neuritis" | "visual_field_defect" | "diplopia" | "papilledema" | "other" | "unknown"; laterality: "right" | "left" | "bilateral" | "unknown"; acuityChange: "improved" | "stable" | "worsened" | "unknown"; afferentDefect: "yes" | "no" | "unknown"; specialistAssessment: "confirmed" | "probable" | "not_confirmed" | "unknown" };
export type CohortClinicalData = StrokeClinicalData | MultipleSclerosisClinicalData | AbnormalMovementClinicalData | GuillainBarreClinicalData | MyastheniaGravisClinicalData | MyelopathyClinicalData | NeuroOphthalmologyClinicalData;
export type RadiologicalInvestigation = { modality: "mri" | "ct" | "cta" | "mra" | "dsa" | "doppler" | "pet" | "spect" | "xray" | "other"; bodyRegion: "brain" | "spine" | "cranial_nerves" | "cerebral_vessels" | "other"; keyFinding: string; lesionStatus: "present" | "absent" | "indeterminate" | "not_applicable"; reportReference?: string | null };
export type ResearchFile = { fileName: string; storageKey: string; url: string; mimeType: string; sizeBytes: number; category: "radiology_image" | "radiology_report" | "laboratory_report" | "other"; uploadedAt: string; uploadedByUserId: number };
export type LaboratoryInvestigation = { testName: "thyroid_function" | "uric_acid" | "ck" | "b12_folate" | "glucose_hba1c" | "electrolytes" | "inflammatory_markers" | "autoimmune_panel" | "other"; resultStatus: "normal" | "abnormal" | "borderline" | "not_done" | "unknown"; resultSummary?: string | null };
export type NeurologicalInvestigation = { testName: "emg_ncs" | "csf_analysis" | "fundus_examination" | "eeg" | "evoked_potentials" | "genetic_testing" | "cognitive_assessment" | "other"; resultStatus: "normal" | "abnormal" | "borderline" | "not_done" | "unknown"; resultSummary?: string | null; lowerMotorNeuronRelevant?: boolean };
export type PatientFollowUp = { visitType: "baseline" | "routine" | "post_discharge" | "emergency" | "telemedicine" | "other"; followUpStatus: "completed" | "scheduled" | "missed" | "lost_to_follow_up" | "withdrawn"; outcome: "improved" | "stable" | "worsened" | "recurrence" | "deceased" | "unknown"; assessmentSummary: string; nextFollowUpPlan?: string | null; timepoint: "baseline" | "1_month" | "3_months" | "6_months" | "12_months" | "annual" | "unscheduled" };

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), accessStatus: mysqlEnum("accessStatus", ["pending", "approved", "suspended"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const patientRecords = mysqlTable("patient_records", {
  id: int("id").autoincrement().primaryKey(), researchId: varchar("researchId", { length: 24 }).notNull().unique(), cohort: mysqlEnum("cohort", ["stroke", "multiple_sclerosis", "abnormal_movements", "guillain_barre", "myasthenia_gravis", "myelopathy", "neuro_ophthalmology"]).notNull(), sex: mysqlEnum("sex", ["female", "male", "intersex", "not_recorded"]).notNull(), ageAtEnrollment: int("ageAtEnrollment").notNull(), ageAtOnset: int("ageAtOnset"), consentStatus: mysqlEnum("consentStatus", ["consented", "pending", "declined", "withdrawn"]).notNull(), enrollmentStatus: mysqlEnum("enrollmentStatus", ["screened", "enrolled", "completed", "withdrawn", "ineligible"]).notNull(), clinicalStatus: mysqlEnum("clinicalStatus", ["active", "follow_up", "completed", "deceased", "unknown"]).notNull(), primaryDiagnosis: varchar("primaryDiagnosis", { length: 160 }).notNull(), dataQualityStatus: mysqlEnum("dataQualityStatus", ["draft", "complete", "query"]).default("draft").notNull(), clinicalData: json("clinicalData").$type<CohortClinicalData>().notNull(), radiologicalInvestigations: json("radiologicalInvestigations").$type<RadiologicalInvestigation[]>().notNull(), laboratoryInvestigations: json("laboratoryInvestigations").$type<LaboratoryInvestigation[]>().notNull(), neurologicalInvestigations: json("neurologicalInvestigations").$type<NeurologicalInvestigation[]>().notNull(), followUpVisits: json("followUpVisits").$type<PatientFollowUp[]>().notNull(), researchFiles: json("researchFiles").$type<ResearchFile[]>().notNull(), createdByUserId: int("createdByUserId").notNull(), lastModifiedByUserId: int("lastModifiedByUserId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const registryAuditLogs = mysqlTable("registry_audit_logs", { id: int("id").autoincrement().primaryKey(), patientRecordId: int("patientRecordId"), actorUserId: int("actorUserId").notNull(), action: mysqlEnum("action", ["created", "updated", "exported", "access_changed"]).notNull(), fieldSummary: varchar("fieldSummary", { length: 500 }).notNull(), occurredAt: timestamp("occurredAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type PatientRecord = typeof patientRecords.$inferSelect;
export type InsertPatientRecord = typeof patientRecords.$inferInsert;
