import { z } from "zod";
import type { CohortClinicalData, PatientRecord, RadiologicalInvestigation } from "../drizzle/schema";

export const cohortSchema = z.enum(["stroke", "neurovascular_compression_syndrome", "vessel_disease", "epilepsy", "neurodegenerative", "abnormal_movement"]);
const choice = <T extends readonly [string, ...string[]]>(values: T) => z.enum(values);
const strokeClinicalSchema = z.object({ cohort: z.literal("stroke"), strokeType: choice(["ischemic", "hemorrhagic", "tia", "other", "unknown"]), vascularTerritory: choice(["anterior", "posterior", "multiple", "unknown"]), nihssAtPresentation: z.number().int().min(0).max(42).nullable().optional(), mRsAtDischarge: z.number().int().min(0).max(6).nullable().optional(), reperfusionTherapy: choice(["none", "iv_thrombolysis", "mechanical_thrombectomy", "both", "unknown"]), toastEtiology: choice(["large_artery", "cardioembolic", "small_vessel", "other_determined", "undetermined", "unknown"]) });
const compressionClinicalSchema = z.object({ cohort: z.literal("neurovascular_compression_syndrome"), compressionSite: choice(["trigeminal_nerve", "facial_nerve", "vestibulocochlear_nerve", "other", "unknown"]), symptomPattern: choice(["paroxysmal", "continuous", "mixed", "unknown"]), imagingConfirmed: choice(["yes", "no", "not_done", "unknown"]), surgicalIntervention: choice(["none", "microvascular_decompression", "other", "unknown"]) });
const vesselClinicalSchema = z.object({ cohort: z.literal("vessel_disease"), diseaseType: choice(["atherosclerotic", "vasculitis", "dissection", "aneurysm", "other", "unknown"]), vascularBed: choice(["intracranial", "extracranial", "systemic", "unknown"]), diagnosticMethod: choice(["angiography", "mri", "ct", "ultrasound", "clinical", "unknown"]), intervention: choice(["none", "medical", "endovascular", "surgical", "unknown"]) });
const epilepsyClinicalSchema = z.object({ cohort: z.literal("epilepsy"), epilepsyType: choice(["focal", "generalized", "combined", "unknown"]), seizureFrequency: choice(["none", "monthly_or_less", "weekly", "daily", "unknown"]), seizureControl: choice(["controlled", "partially_controlled", "uncontrolled", "unknown"]), eegAbnormality: choice(["yes", "no", "not_done", "unknown"]), treatmentResponse: choice(["responsive", "partially_responsive", "drug_resistant", "unknown"]) });
const neurodegenerativeClinicalSchema = z.object({ cohort: z.literal("neurodegenerative"), diseaseSubtype: choice(["parkinson_disease", "alzheimers_disease", "motor_neuron_disease", "multiple_system_atrophy", "other", "unknown"]), diseaseStage: choice(["early", "moderate", "advanced", "unknown"]), cognitiveInvolvement: choice(["yes", "no", "unknown"]), geneticTesting: choice(["positive", "negative", "not_done", "unknown"]), progressionPattern: choice(["slow", "moderate", "rapid", "unknown"]) });
const movementClinicalSchema = z.object({ cohort: z.literal("abnormal_movement"), movementPhenotype: choice(["tremor", "dystonia", "chorea", "ataxia", "tics", "other", "unknown"]), distribution: choice(["focal", "segmental", "generalized", "unknown"]), severity: choice(["mild", "moderate", "severe", "unknown"]), functionalImpact: choice(["none", "mild", "moderate", "severe", "unknown"]), treatmentResponse: choice(["responsive", "partially_responsive", "refractory", "unknown"]) });
export const clinicalDataSchema = z.discriminatedUnion("cohort", [strokeClinicalSchema, compressionClinicalSchema, vesselClinicalSchema, epilepsyClinicalSchema, neurodegenerativeClinicalSchema, movementClinicalSchema]);

export const radiologicalInvestigationSchema = z.object({ modality: choice(["mri", "ct", "cta", "mra", "dsa", "doppler", "pet", "spect", "xray", "other"]), bodyRegion: choice(["brain", "spine", "cranial_nerves", "cerebral_vessels", "other"]), keyFinding: z.string().trim().min(2).max(500), lesionStatus: choice(["present", "absent", "indeterminate", "not_applicable"]), reportReference: z.string().trim().regex(/^RAD-[A-Z0-9-]{3,24}$/, "Use a non-identifying reference such as RAD-2026-001.").nullable().optional() });
const radiologyListSchema = z.array(radiologicalInvestigationSchema).max(20);
export const patientInputSchema = z.object({ researchId: z.string().trim().toUpperCase().regex(/^EGR-[A-Z0-9]{4,16}$/, "Use the format EGR-XXXX."), cohort: cohortSchema, sex: z.enum(["female", "male", "intersex", "not_recorded"]), ageAtEnrollment: z.number().int().min(0).max(120), ageAtOnset: z.number().int().min(0).max(120).nullable().optional(), consentStatus: z.enum(["consented", "pending", "declined", "withdrawn"]), enrollmentStatus: z.enum(["screened", "enrolled", "completed", "withdrawn", "ineligible"]), clinicalStatus: z.enum(["active", "follow_up", "completed", "deceased", "unknown"]), primaryDiagnosis: z.string().trim().min(2).max(160), dataQualityStatus: z.enum(["draft", "complete", "query"]), clinicalData: clinicalDataSchema, radiologicalInvestigations: radiologyListSchema }).superRefine((value, context) => { if (value.cohort !== value.clinicalData.cohort) context.addIssue({ code: "custom", path: ["clinicalData", "cohort"], message: "Clinical data must match the selected cohort." }); if (value.ageAtOnset !== null && value.ageAtOnset !== undefined && value.ageAtOnset > value.ageAtEnrollment) context.addIssue({ code: "custom", path: ["ageAtOnset"], message: "Age at onset cannot exceed age at enrolment." }); });
export const patientUpdateSchema = patientInputSchema.safeExtend({ id: z.number().int().positive() });
export const registryFiltersSchema = z.object({ cohort: cohortSchema.optional(), consentStatus: z.enum(["consented", "pending", "declined", "withdrawn"]).optional(), enrollmentStatus: z.enum(["screened", "enrolled", "completed", "withdrawn", "ineligible"]).optional(), clinicalStatus: z.enum(["active", "follow_up", "completed", "deceased", "unknown"]).optional(), dataQualityStatus: z.enum(["draft", "complete", "query"]).optional(), search: z.string().trim().max(24).optional(), ageMin: z.number().int().min(0).max(120).optional(), ageMax: z.number().int().min(0).max(120).optional() }).optional();
export function toAgeBand(age: number): string { if (age < 18) return "0-17"; if (age < 30) return "18-29"; if (age < 40) return "30-39"; if (age < 50) return "40-49"; if (age < 60) return "50-59"; if (age < 70) return "60-69"; if (age < 80) return "70-79"; return "80+"; }
function cleanValue(value: string | number | boolean | null | undefined): string | number | boolean | null { return value ?? null; }
export function toDeidentifiedExportRow(record: PatientRecord) { const clinicalData = record.clinicalData as CohortClinicalData; const base = { research_id: record.researchId, cohort: record.cohort, age_band_at_enrollment: toAgeBand(record.ageAtEnrollment), age_band_at_onset: record.ageAtOnset === null ? null : toAgeBand(record.ageAtOnset), consent_status: record.consentStatus, enrollment_status: record.enrollmentStatus, clinical_status: record.clinicalStatus, primary_diagnosis: record.primaryDiagnosis, data_quality_status: record.dataQualityStatus, radiological_investigations: ((record.radiologicalInvestigations as RadiologicalInvestigation[] | null | undefined) ?? []).map(investigation => ({ modality: investigation.modality, body_region: investigation.bodyRegion, key_finding: investigation.keyFinding, lesion_status: investigation.lesionStatus })) };
  switch (clinicalData.cohort) {
    case "stroke": return { ...base, stroke_type: clinicalData.strokeType, vascular_territory: clinicalData.vascularTerritory, nihss_at_presentation: cleanValue(clinicalData.nihssAtPresentation), mrs_at_discharge: cleanValue(clinicalData.mRsAtDischarge), reperfusion_therapy: clinicalData.reperfusionTherapy, toast_etiology: clinicalData.toastEtiology };
    case "neurovascular_compression_syndrome": return { ...base, compression_site: clinicalData.compressionSite, symptom_pattern: clinicalData.symptomPattern, imaging_confirmed: clinicalData.imagingConfirmed, surgical_intervention: clinicalData.surgicalIntervention };
    case "vessel_disease": return { ...base, vessel_disease_type: clinicalData.diseaseType, vascular_bed: clinicalData.vascularBed, diagnostic_method: clinicalData.diagnosticMethod, intervention: clinicalData.intervention };
    case "epilepsy": return { ...base, epilepsy_type: clinicalData.epilepsyType, seizure_frequency: clinicalData.seizureFrequency, seizure_control: clinicalData.seizureControl, eeg_abnormality: clinicalData.eegAbnormality, treatment_response: clinicalData.treatmentResponse };
    case "neurodegenerative": return { ...base, disease_subtype: clinicalData.diseaseSubtype, disease_stage: clinicalData.diseaseStage, cognitive_involvement: clinicalData.cognitiveInvolvement, genetic_testing: clinicalData.geneticTesting, progression_pattern: clinicalData.progressionPattern };
    case "abnormal_movement": return { ...base, movement_phenotype: clinicalData.movementPhenotype, distribution: clinicalData.distribution, severity: clinicalData.severity, functional_impact: clinicalData.functionalImpact, treatment_response: clinicalData.treatmentResponse };
  }
}
