import { describe, expect, it, vi } from "vitest";
import type { PatientRecord } from "../drizzle/schema";
import type { TrpcContext } from "./_core/context";
import { getCompleteRecordThresholdError, getInvestigationCoverage, getPatientUpdateAuditSummary, getResearchRecordCompleteness, patientInputSchema, patientUpdateSchema, researchFileInputSchema, toDeidentifiedExportRow } from "./registry";
import { appRouter } from "./routers";
import * as db from "./db";
import * as notifications from "./_core/notification";
import { updatePatientRecordWithDb } from "./db";
import { ENV } from "./_core/env";

function context(role: "admin" | "user", accessStatus: "pending" | "approved" | "suspended"): TrpcContext { return { user: { id: 14, openId: "test-user", name: "Test User", email: "test@example.com", loginMethod: "manus", role, accessStatus, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] }; }
const base = { sex: "not_recorded", ageAtEnrollment: 50, ageAtOnset: 48, consentStatus: "consented", enrollmentStatus: "enrolled", clinicalStatus: "active", primaryDiagnosis: "Research diagnosis", dataQualityStatus: "draft", completenessStatus: "incomplete", missingItems: ["follow_up"], completionOwnerUserId: null, briefClinicalHistory: null, positiveExaminationFindings: null, dischargeTreatment: null, immuneTherapies: [], msDoseAdherence: [], radiologicalInvestigations: [], laboratoryInvestigations: [], neurologicalInvestigations: [], protocolInvestigations: [], followUpVisits: [] } as const;
const newResearchId = "MUNR-0000000000000000000000001";
const stroke = { cohort: "stroke", strokeType: "ischemic", vascularTerritory: "mca_complete", reperfusionTherapy: "none", toastEtiology: "unknown", majorComplication: "none", strokeEvaluation: "nihss_and_mrs" } as const;
const ms = { cohort: "multiple_sclerosis", diseaseCourse: "relapsing_remitting", disabilityLevel: "mild", relapseActivity: "inactive", diseaseModifyingTherapy: "ocrelizumab", msfcAssessed: "yes", timed25FootWalkSeconds: 10, nineHolePegTestSeconds: 24, pasat3Score: 42, tuberculinScreen: "negative", chestTuberculosisScreen: "clear", msEvaluation: "clinical_mri_msfc" } as const;
const cidp = { cohort: "cidp", variant: "madsam", diagnosticPathway: "vasculitic_neuropathy", disabilityLevel: "moderate", emgNcsEvidence: "axonal_multifocal", csfProteinStatus: "elevated", cidpEvaluation: "vasculitis_workup" } as const;

describe("Mansoura University registry validation", () => {
  it("requires a pseudonymised MUNR Research ID with exactly 25 digits and rejects other formats", () => { expect(patientInputSchema.shape.researchId.safeParse(newResearchId).success).toBe(true); expect(patientInputSchema.shape.researchId.safeParse("munr-1234567890123456789012345").success).toBe(true); expect(patientInputSchema.shape.researchId.safeParse("MUNR-123456789012345678901234").success).toBe(false); expect(patientInputSchema.shape.researchId.safeParse("MUNR-12345678901234567890123456").success).toBe(false); expect(patientInputSchema.shape.researchId.safeParse("MUNR-2026A").success).toBe(false); expect(patientInputSchema.shape.researchId.safeParse("AHMED-MRN-12345").success).toBe(false); });
  it("accepts all approved neurology cohorts including CIDP", () => {
    const cases = [
      ["stroke", stroke], ["ms", ms], ["movement", { cohort: "abnormal_movements", movementPhenotype: "tremor", distribution: "focal", severity: "mild", functionalImpact: "mild", treatmentResponse: "responsive", movementEvaluation: "phenomenology_only" }], ["gbs", { cohort: "guillain_barre", variant: "aidp", disabilityScore: "2", ventilatorySupport: "none", treatment: "ivig", gbsEvaluation: "gbs_disability_only" }], ["mg", { cohort: "myasthenia_gravis", mgfaClass: "II", antibodyStatus: "achr", thymomaStatus: "absent", crisisHistory: "never", treatmentResponse: "responsive", mgEvaluation: "mgfa_only" }], ["myelopathy", { cohort: "myelopathy", level: "cervical", cause: "compressive", upperMotorNeuronSigns: "present", lowerMotorNeuronFeatures: "absent", bladderInvolvement: "no", myelopathyEvaluation: "mri_and_neuroexam" }], ["neurooph", { cohort: "neuro_ophthalmology", visualSyndrome: "optic_neuritis", laterality: "right", acuityChange: "stable", afferentDefect: "yes", diseaseClassification: "nmosd", antibodyProfile: "aqp4_positive", linkedSystemicDisease: "none", neuroOphEvaluation: "antibody_workup" }], ["cidp", cidp],
    ] as const;
    const additionalFocusByCohort: Record<string, string> = { stroke: "acute_complication_course", multiple_sclerosis: "treatment_safety", abnormal_movements: "trigger_or_exposure", guillain_barre: "autonomic_involvement", myasthenia_gravis: "bulbar_respiratory_risk", myelopathy: "red_flag_neurology", neuro_ophthalmology: "optic_disc_retinal_finding", cidp: "disability_trajectory" };
    for (const [suffix, clinicalData] of cases) expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: clinicalData.cohort, clinicalData: { ...clinicalData, additionalResearchFocus: additionalFocusByCohort[clinicalData.cohort], additionalResearchInformation: "Cohort-relevant research detail" } }).success, suffix).toBe(true);
  });
  it("accepts expanded medically relevant selector values only in their matching cohort fields", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, vascularTerritory: "lacunar_deep", majorComplication: "hydrocephalus", strokeEvaluation: "nihss_mrs_barthel" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "multiple_sclerosis", clinicalData: { ...ms, relapseActivity: "progression_without_relapse", diseaseModifyingTherapy: "ozanimod", msEvaluation: "clinical_mri_msfc_edss" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "abnormal_movements", clinicalData: { cohort: "abnormal_movements", movementPhenotype: "myoclonus", distribution: "multifocal", severity: "moderate", functionalImpact: "moderate", treatmentResponse: "not_treated", movementEvaluation: "phenomenology_video_scale" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "guillain_barre", clinicalData: { cohort: "guillain_barre", variant: "pharyngeal_cervical_brachial", disabilityScore: "3", ventilatorySupport: "tracheostomy", treatment: "observation", gbsEvaluation: "brighton_level_recorded" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "myasthenia_gravis", clinicalData: { cohort: "myasthenia_gravis", mgfaClass: "IIIb", antibodyStatus: "titin", thymomaStatus: "thymic_hyperplasia", crisisHistory: "impending", treatmentResponse: "intolerant", mgEvaluation: "mgfa_qmg_mgadl" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "myelopathy", clinicalData: { cohort: "myelopathy", level: "conus", cause: "vascular_malformation", upperMotorNeuronSigns: "present", lowerMotorNeuronFeatures: "absent", bladderInvolvement: "retention", myelopathyEvaluation: "mri_vascular_imaging" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "neuro_ophthalmology", clinicalData: { cohort: "neuro_ophthalmology", visualSyndrome: "ischemic_optic_neuropathy", laterality: "bilateral", acuityChange: "severely_reduced", afferentDefect: "yes", diseaseClassification: "sarcoid_optic_neuropathy", antibodyProfile: "indeterminate", linkedSystemicDisease: "behcet_disease", neuroOphEvaluation: "acuity_colour_vision_oct" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "cidp", clinicalData: { ...cidp, variant: "sensory_motor", diagnosticPathway: "possible_cidp", emgNcsEvidence: "conduction_block", csfProteinStatus: "markedly_elevated", cidpEvaluation: "serial_incat_onls" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, strokeType: "aidp" } }).success).toBe(false);
  });
  it("captures stroke complications, MS pre-immunosuppression screening and dated dose adherence", () => {
    const parsed = patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "multiple_sclerosis", clinicalData: { ...ms, relapseActivity: "active" }, immuneTherapies: [{ therapyClass: "b_cell_depleting", agent: "Ocrelizumab", status: "active", startDate: "2026-08-01", infectionExclusionStatus: "cleared", infectionExclusionNote: "Protocol review documented" }], msDoseAdherence: [{ therapyName: "Ocrelizumab", doseDate: "2026-08-01", doseStatus: "taken" }], protocolInvestigations: [{ itemCode: "infection_exclusion_pre_immunotherapy", status: "completed" }] });
    expect(parsed.success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "multiple_sclerosis", clinicalData: ms, radiologicalInvestigations: [{ modality: "xray", bodyRegion: "chest", keyFinding: "Screening review", lesionStatus: "not_applicable" }], laboratoryInvestigations: [{ testName: "varicella_immunity", resultStatus: "normal" }], protocolInvestigations: [{ itemCode: "chest_imaging_pre_immunotherapy", status: "completed" }, { itemCode: "tuberculin_tb_screen_pre_immunotherapy", status: "completed" }, { itemCode: "varicella_immunity_pre_immunotherapy", status: "completed" }] }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, vascularTerritory: "vertebrobasilar", majorComplication: "aspiration_pneumonia" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-00000000000009", cohort: "stroke", clinicalData: stroke, msDoseAdherence: [{ therapyName: "Interferon", doseDate: "2026-08-01", doseStatus: "missed" }] }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-00000000000010", cohort: "multiple_sclerosis", clinicalData: ms, immuneTherapies: [{ therapyClass: "biologic", status: "planned", infectionExclusionStatus: "invalid" }] }).success).toBe(false);
  });
  it("records only the explicit evaluation items relevant to the selected cohort", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, evaluationItems: [{ code: "stroke_nihss", label: "Stroke NIHSS", status: "recorded", value: "12" }, { code: "stroke_mrs", label: "Stroke modified Rankin Scale (mRS)", status: "recorded", value: "3" }] } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-00000000000011", cohort: "stroke", clinicalData: { ...stroke, evaluationItems: [{ code: "ms_edss", label: "MS EDSS disability", status: "recorded", value: "3.5" }] } }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "cidp", clinicalData: { ...cidp, evaluationItems: [{ code: "cidp_variant_pattern", label: "CIDP variant pattern", status: "recorded", value: "MADSAM" }, { code: "cidp_incat_onls", label: "CIDP INCAT / ONLS disability", status: "recorded", value: "5" }, { code: "cidp_vasculitic_features", label: "CIDP vasculitic features", status: "not_assessed" }] } }).success).toBe(true);
  });
  it("captures NMOSD, MOGAD, GCA, mononeuritis multiplex, and vasculitic-neuropathy pathways", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "neuro_ophthalmology", clinicalData: { cohort: "neuro_ophthalmology", visualSyndrome: "optic_neuritis", laterality: "left", acuityChange: "worsened", afferentDefect: "yes", diseaseClassification: "giant_cell_arteritis", antibodyProfile: "not_done", linkedSystemicDisease: "systemic_vasculitis", neuroOphEvaluation: "gca_pathway" }, immuneTherapies: [{ therapyClass: "corticosteroid", status: "active" }] }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "cidp", clinicalData: { ...cidp, diagnosticPathway: "mononeuritis_multiplex" }, neurologicalInvestigations: [{ testName: "nerve_biopsy", resultStatus: "abnormal" }] }).success).toBe(true);
  });
  it("enforces completion workflow consistency", () => { expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-00000000000012", cohort: "cidp", completenessStatus: "complete", missingItems: ["laboratory"], clinicalData: cidp }).success).toBe(false); });
  it("requires 85% assessed-field completion before a record can be marked complete while allowing a draft", () => {
    const incomplete = { ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, strokeType: "unknown", vascularTerritory: "unknown", strokeEvaluation: "unknown" }, missingItems: [], dataQualityStatus: "complete", completenessStatus: "complete" };
    expect(getResearchRecordCompleteness(incomplete).percentage).toBeLessThan(85);
    expect(getCompleteRecordThresholdError(incomplete)).toContain("at least 85%");
    expect(getCompleteRecordThresholdError({ ...incomplete, dataQualityStatus: "draft", completenessStatus: "incomplete" })).toBeNull();
    const complete = { ...base, researchId: newResearchId, cohort: "stroke", clinicalData: stroke, missingItems: [], dataQualityStatus: "complete", completenessStatus: "complete" };
    expect(getResearchRecordCompleteness(complete).percentage).toBeGreaterThanOrEqual(85);
    expect(getCompleteRecordThresholdError(complete)).toBeNull();
    expect(getCompleteRecordThresholdError({ ...complete, missingItems: ["follow_up"] })).toContain("cannot retain items still required");
  });
  it("accepts research-safe additional cohort information but rejects direct identifiers", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, additionalResearchInformation: "Protocol-relevant classification detail" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, additionalResearchInformation: "Patient name is included" } }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, additionalResearchInformation: "Contact 01012345678" } }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, additionalResearchInformation: "Email researcher@example.org" } }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "stroke", clinicalData: { ...stroke, additionalResearchInformation: "National ID 12345678901234" } }).success).toBe(false);
  });
  it("rejects an additional research focus that belongs to another cohort", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: newResearchId, cohort: "multiple_sclerosis", clinicalData: { ...ms, additionalResearchFocus: "acute_complication_course" } }).success).toBe(false);
  });
  it("allows existing 14-digit MUNR records to be updated unchanged", () => {
    expect(patientUpdateSchema.safeParse({ ...base, id: 7, researchId: "MUNR-00000000000001", cohort: "stroke", clinicalData: stroke }).success).toBe(true);
  });
  it("summarises radiology, laboratory, neurological, and protocol investigation coverage for the overview", () => { const coverage = getInvestigationCoverage([{ radiologicalInvestigations: [{}], laboratoryInvestigations: [{}], neurologicalInvestigations: [{}], protocolInvestigations: [{ status: "completed" }, { status: "not_indicated" }] }, { radiologicalInvestigations: [], laboratoryInvestigations: [{}], neurologicalInvestigations: [], protocolInvestigations: [{ status: "ordered" }] }]); expect(coverage).toEqual({ totalRecords: 2, radiologyRecorded: 1, laboratoryRecorded: 2, neurologicalRecorded: 1, protocolChecklistComplete: 1, protocolChecklistOutstanding: 1 }); });
  it("exports research-safe summaries while excluding clinical narratives, adherence dates, completion ownership, and research files", () => {
    const row = toDeidentifiedExportRow({ id: 7, researchId: "MUNR-STROKE26", cohort: "stroke", sex: "male", ageAtEnrollment: 64, ageAtOnset: 63, consentStatus: "consented", enrollmentStatus: "enrolled", clinicalStatus: "active", dataQualityStatus: "complete", completenessStatus: "incomplete", missingItems: ["follow_up"], completionOwnerUserId: 33, primaryDiagnosis: "Ischaemic stroke", briefClinicalHistory: "Sensitive narrative", positiveExaminationFindings: "Sensitive findings", dischargeTreatment: "Sensitive plan", immuneTherapies: [{ therapyClass: "corticosteroid", status: "completed", agent: "Prednisone", startDate: "2026-01-01" }], msDoseAdherence: [], clinicalData: stroke, radiologicalInvestigations: [{ modality: "mri", bodyRegion: "brain", keyFinding: "Focal lesion", lesionStatus: "present", reportReference: "RAD-2026-001" }], laboratoryInvestigations: [{ testName: "hba1c", resultStatus: "abnormal", resultSummary: "Above local reference range" }], neurologicalInvestigations: [{ testName: "fundus_examination", resultStatus: "normal" }], protocolInvestigations: [{ itemCode: "vascular_imaging", status: "completed" }], followUpVisits: [{ visitType: "routine", followUpStatus: "completed", outcome: "stable", assessmentSummary: "Stable", timepoint: "3_months" }], researchFiles: [{ fileName: "RAD-2026-001.pdf", storageKey: "key", url: "url", mimeType: "application/pdf", sizeBytes: 4, category: "radiology_report", uploadedAt: "2026-01-01", uploadedByUserId: 14 }], createdByUserId: 1, lastModifiedByUserId: 2, createdAt: new Date(), updatedAt: new Date() } as PatientRecord);
    expect(row).toMatchObject({ research_id: "MUNR-STROKE26", age_band_at_enrollment: "60-69", vascular_territory: "mca_complete", major_complication: "none", completeness_status: "incomplete" }); expect(row).not.toHaveProperty("completionOwnerUserId"); expect(row).not.toHaveProperty("createdByUserId"); expect(row).not.toHaveProperty("lastModifiedByUserId"); expect(row).not.toHaveProperty("recordedBy"); expect(row).not.toHaveProperty("additional_research_information"); expect(row).not.toHaveProperty("additional_research_focus"); expect(row).not.toHaveProperty("research_files"); expect(row).not.toHaveProperty("briefClinicalHistory"); expect(row).not.toHaveProperty("msDoseAdherence"); expect(row.immune_therapies).toEqual([{ therapy_class: "corticosteroid", agent: "Prednisone", status: "completed" }]); expect(row.cohort_evaluation_statuses).toEqual([]);
  });
  it("protects upload metadata and enforces allowed file types and size", () => { expect(researchFileInputSchema.safeParse({ patientRecordId: 1, fileName: "RAD-2026-001.pdf", mimeType: "application/pdf", sizeBytes: 1024, category: "radiology_report", contentBase64: "YWJjZA==" }).success).toBe(true); expect(researchFileInputSchema.safeParse({ patientRecordId: 1, fileName: "patient-name.pdf", mimeType: "application/pdf", sizeBytes: 1024, category: "radiology_report", contentBase64: "YWJjZA==" }).success).toBe(false); });
  it("writes an audit event that identifies histories, immune therapy, adherence, discharge treatment and follow-up changes", async () => { const auditRows: unknown[] = []; let selected = 0; const fakeDb: any = { select: () => ({ from: () => ({ where: () => ({ limit: async () => { selected += 1; return selected === 1 ? [{ id: 7 }] : [{ id: 7, researchId: "MUNR-FOLLOW26" }]; } }) }) }), update: () => ({ set: () => ({ where: async () => undefined }) }), insert: () => ({ values: async (row: unknown) => auditRows.push(row) }) }; const input: any = { ...base, researchId: "MUNR-FOLLOW26", cohort: "multiple_sclerosis", briefClinicalHistory: "History", positiveExaminationFindings: "Findings", dischargeTreatment: "Treatment", immuneTherapies: [{ therapyClass: "ivig", status: "active" }], msDoseAdherence: [{ therapyName: "DMT", doseDate: "2026-08-01", doseStatus: "taken" }], clinicalData: ms, followUpVisits: [{ visitType: "routine", followUpStatus: "completed", outcome: "stable", assessmentSummary: "Stable", timepoint: "3_months" }] }; await updatePatientRecordWithDb(fakeDb, 7, input, 14); expect(auditRows).toHaveLength(1); expect(auditRows[0]).toMatchObject({ patientRecordId: 7, actorUserId: 14, action: "updated" }); expect(getPatientUpdateAuditSummary(input)).toContain("immune therapy"); });
  it("blocks pending users and permits an approved administrator to approve a new user", async () => { await expect(appRouter.createCaller(context("user", "pending")).registry.overview()).rejects.toMatchObject({ code: "FORBIDDEN" }); const target = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 27, openId: "new-oauth-account", role: "user", accessStatus: "pending", removedAt: null }); const setAccess = vi.spyOn(db, "setUserAccessStatus").mockResolvedValue(undefined); const logAccess = vi.spyOn(db, "logAccessChange").mockResolvedValue(undefined); try { await expect(appRouter.createCaller(context("admin", "approved")).administration.setAccess({ userId: 27, accessStatus: "approved" })).resolves.toEqual({ success: true }); expect(setAccess).toHaveBeenCalledWith(27, "approved"); } finally { target.mockRestore(); setAccess.mockRestore(); logAccess.mockRestore(); } });
  it("allows only approved administrators to grant a second OAuth account the administrator role", async () => { const target = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 27, openId: "second-oauth-account", role: "user", accessStatus: "approved" }); const setRole = vi.spyOn(db, "setUserRole").mockResolvedValue(undefined); const logRole = vi.spyOn(db, "logRoleChange").mockResolvedValue(undefined); try { await expect(appRouter.createCaller(context("user", "approved")).administration.setRole({ userId: 27, role: "admin" })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.setRole({ userId: 27, role: "admin" })).resolves.toEqual({ success: true }); expect(setRole).toHaveBeenCalledWith(27, "admin"); expect(logRole).toHaveBeenCalledWith(14, 27, "admin"); } finally { target.mockRestore(); setRole.mockRestore(); logRole.mockRestore(); } });
  it("rejects administrator promotion before approval and prevents administrator self-demotion", async () => { const target = vi.spyOn(db, "getUserAdministrationState"); const setRole = vi.spyOn(db, "setUserRole").mockResolvedValue(undefined); const logRole = vi.spyOn(db, "logRoleChange").mockResolvedValue(undefined); try { target.mockResolvedValueOnce({ id: 27, openId: "pending-oauth-account", role: "user", accessStatus: "pending" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.setRole({ userId: 27, role: "admin" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); target.mockResolvedValueOnce({ id: 14, openId: "test-user", role: "admin", accessStatus: "approved" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.setRole({ userId: 14, role: "user" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(setRole).not.toHaveBeenCalled(); expect(logRole).not.toHaveBeenCalled(); } finally { target.mockRestore(); setRole.mockRestore(); logRole.mockRestore(); } });
  it("rejects every access, role, and removal mutation aimed at the configured owner, even from another administrator", async () => {
    const previousOwnerOpenId = ENV.ownerOpenId;
    (ENV as { ownerOpenId?: string }).ownerOpenId = "configured-owner-oauth";
    const target = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 27, openId: "configured-owner-oauth", role: "admin", accessStatus: "approved", removedAt: null });
    const setAccess = vi.spyOn(db, "setUserAccessStatus").mockResolvedValue(undefined);
    const setRole = vi.spyOn(db, "setUserRole").mockResolvedValue(undefined);
    const remove = vi.spyOn(db, "removeUserFromRegistry").mockResolvedValue(undefined);
    try {
      const caller = appRouter.createCaller(context("admin", "approved"));
      await expect(caller.administration.setAccess({ userId: 27, accessStatus: "suspended" })).rejects.toMatchObject({ code: "BAD_REQUEST" });
      await expect(caller.administration.setRole({ userId: 27, role: "user" })).rejects.toMatchObject({ code: "BAD_REQUEST" });
      await expect(caller.administration.removeProjectAccount({ userId: 27, confirmed: true })).rejects.toMatchObject({ code: "BAD_REQUEST" });
      expect(setAccess).not.toHaveBeenCalled();
      expect(setRole).not.toHaveBeenCalled();
      expect(remove).not.toHaveBeenCalled();
    } finally {
      (ENV as { ownerOpenId?: string }).ownerOpenId = previousOwnerOpenId;
      target.mockRestore(); setAccess.mockRestore(); setRole.mockRestore(); remove.mockRestore();
    }
  });
  it("requires an approved administrator, an explicit confirmation, and a different active account for project-account removal", async () => { const target = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 27, openId: "second-oauth-account", role: "admin", accessStatus: "approved", removedAt: null }); const remove = vi.spyOn(db, "removeUserFromRegistry").mockResolvedValue(undefined); const logRemoval = vi.spyOn(db, "logProjectAccountRemoval").mockResolvedValue(undefined); try { await expect(appRouter.createCaller(context("user", "approved")).administration.removeProjectAccount({ userId: 27, confirmed: true })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.removeProjectAccount({ userId: 27, confirmed: false } as any)).rejects.toMatchObject({ code: "BAD_REQUEST" }); target.mockResolvedValueOnce({ id: 14, openId: "test-user", role: "admin", accessStatus: "approved", removedAt: null }); await expect(appRouter.createCaller(context("admin", "approved")).administration.removeProjectAccount({ userId: 14, confirmed: true })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.removeProjectAccount({ userId: 27, confirmed: true })).resolves.toEqual({ success: true }); expect(remove).toHaveBeenCalledWith(27, 14); expect(logRemoval).toHaveBeenCalledWith(14, 27); } finally { target.mockRestore(); remove.mockRestore(); logRemoval.mockRestore(); } });
  it("does not remove an account already removed from the active project list", async () => { const target = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 27, openId: "second-oauth-account", role: "user", accessStatus: "suspended", removedAt: new Date() }); const remove = vi.spyOn(db, "removeUserFromRegistry").mockResolvedValue(undefined); try { await expect(appRouter.createCaller(context("admin", "approved")).administration.removeProjectAccount({ userId: 27, confirmed: true })).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(remove).not.toHaveBeenCalled(); } finally { target.mockRestore(); remove.mockRestore(); } });
  it("resets a removed non-owner OAuth account to a new pending applicant rather than restoring prior access", () => {
    expect(db.getRemovedAccountReapplicationReset(false, new Date())).toEqual({ role: "user", accessStatus: "pending", removedAt: null, removedByAdminId: null });
    expect(db.getRemovedAccountReapplicationReset(false, null)).toBeNull();
    expect(db.getRemovedAccountReapplicationReset(true, new Date())).toBeNull();
  });
  it("returns OAuth-derived applicant review fields only to an approved administrator", async () => { const listUsers = vi.spyOn(db, "listUsersForAdmin").mockResolvedValue([{ id: 22, name: "Applicant Name", email: "applicant@example.edu", role: "user", accessStatus: "pending", oauthIdentityLinked: true, lastSignedIn: new Date(), updatedAt: new Date() }]); try { await expect(appRouter.createCaller(context("user", "approved")).administration.users()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("admin", "approved")).administration.users()).resolves.toEqual([expect.objectContaining({ name: "Applicant Name", email: "applicant@example.edu", oauthIdentityLinked: true })]); } finally { listUsers.mockRestore(); } });
  it("limits profile-picture retrieval to approved users and keeps it scoped to the caller", async () => { const getAvatar = vi.spyOn(db, "getOwnProfileAvatar").mockResolvedValue(null); try { await expect(appRouter.createCaller(context("user", "pending")).profile.avatar()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("user", "approved")).profile.avatar()).resolves.toBeNull(); expect(getAvatar).toHaveBeenCalledWith(14); } finally { getAvatar.mockRestore(); } });
  it("accepts a verified image signature only for an approved user's own profile picture", async () => { const replaceAvatar = vi.spyOn(db, "replaceOwnProfileAvatar").mockResolvedValue({ mimeType: "image/png", url: "https://storage.example/avatar.png" }); try { const pending = appRouter.createCaller(context("user", "pending")); await expect(pending.profile.replaceAvatar({ mimeType: "image/png", sizeBytes: 8, contentBase64: "iVBORw0KGgo=" })).rejects.toMatchObject({ code: "FORBIDDEN" }); const approved = appRouter.createCaller(context("user", "approved")); await expect(approved.profile.replaceAvatar({ mimeType: "image/png", sizeBytes: 9, contentBase64: "bm90LWEtcG5n" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(approved.profile.replaceAvatar({ mimeType: "image/png", sizeBytes: 8, contentBase64: "iVBORw0KGgo=" })).resolves.toMatchObject({ mimeType: "image/png" }); expect(replaceAvatar).toHaveBeenCalledWith(14, expect.objectContaining({ mimeType: "image/png", content: expect.any(Buffer) })); } finally { replaceAvatar.mockRestore(); } });
  it("allows approved users to report only the static homepage media issue to the owner", async () => { const notify = vi.spyOn(notifications, "notifyOwner").mockResolvedValue(true); try { await expect(appRouter.createCaller(context("user", "pending")).mediaReports.reportBrokenHomepageHeroImage()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("user", "approved")).mediaReports.reportBrokenHomepageHeroImage()).resolves.toEqual({ success: true, alreadyReported: false }); expect(notify).toHaveBeenCalledWith({ title: "Broken homepage image reported", content: "A registered user reported that the static abstract homepage hero image could not be loaded. No patient, record, user, or clinical data was included." }); await expect(appRouter.createCaller(context("user", "approved")).mediaReports.reportBrokenHomepageHeroImage()).resolves.toEqual({ success: true, alreadyReported: true }); expect(notify).toHaveBeenCalledTimes(1); } finally { notify.mockRestore(); } });
  it("permits messages only for approved users and rejects self-messages and patient-data references", async () => { const recipients = vi.spyOn(db, "listApprovedMessageRecipients").mockResolvedValue([{ id: 22, name: "Approved Colleague", email: "colleague@example.edu", role: "user" }]); const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(true); const send = vi.spyOn(db, "sendDirectMessage").mockResolvedValue({ id: 1, senderUserId: 14, recipientUserId: 22, body: "Please review the protocol checklist.", createdAt: new Date() }); try { await expect(appRouter.createCaller(context("user", "pending")).messages.recipients()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("user", "approved")).messages.recipients()).resolves.toHaveLength(1); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 14, body: "Self message" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 22, body: "Please open MUNR-ABC1234" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 22, body: "Please review the protocol checklist." })).resolves.toMatchObject({ recipientUserId: 22 }); expect(recipients).toHaveBeenCalledWith(14); expect(send).toHaveBeenCalledWith(14, 22, "Please review the protocol checklist."); } finally { recipients.mockRestore(); recipientIsApproved.mockRestore(); send.mockRestore(); } });
  it("blocks message content containing patient-name, phone-number, or national-ID references and rejects unapproved recipients", async () => { const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(true); const send = vi.spyOn(db, "sendDirectMessage").mockResolvedValue({ id: 2, senderUserId: 14, recipientUserId: 22, body: "Protocol meeting at 10:00.", createdAt: new Date() }); try { const caller = appRouter.createCaller(context("user", "approved")); await expect(caller.messages.send({ recipientUserId: 22, body: "Patient name is withheld" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(caller.messages.send({ recipientUserId: 22, body: "Use the patient phone number" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(caller.messages.send({ recipientUserId: 22, body: "National ID review" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); recipientIsApproved.mockResolvedValue(false); await expect(caller.messages.send({ recipientUserId: 22, body: "Protocol meeting at 10:00." })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(send).not.toHaveBeenCalled(); } finally { recipientIsApproved.mockRestore(); send.mockRestore(); } });
  it("does not reveal a direct-message thread when the recipient is not approved", async () => { const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(false); const listThread = vi.spyOn(db, "listDirectMessages").mockResolvedValue([]); try { await expect(appRouter.createCaller(context("user", "approved")).messages.thread({ recipientUserId: 22 })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(listThread).not.toHaveBeenCalled(); } finally { recipientIsApproved.mockRestore(); listThread.mockRestore(); } });
  it("blocks additional direct identifiers in English and Arabic message content", async () => { const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(true); const send = vi.spyOn(db, "sendDirectMessage").mockResolvedValue({ id: 3, senderUserId: 14, recipientUserId: 22, body: "Protocol meeting at 10:00.", createdAt: new Date() }); try { const caller = appRouter.createCaller(context("user", "approved")); for (const body of ["Address is on file", "Home address is on file", "Date of birth is documented", "MRN 14572", "Contact me at name@example.org", "National number 12345678901234", "رقم الهاتف 01012345678", "تاريخ الميلاد مسجل"]) await expect(caller.messages.send({ recipientUserId: 22, body })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(send).not.toHaveBeenCalled(); } finally { recipientIsApproved.mockRestore(); send.mockRestore(); } });
  it("limits task administration to approved administrators and sends only fixed privacy-safe owner alerts", async () => {
    const state = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 22, openId: "approved-member", role: "user", accessStatus: "approved", removedAt: null });
    const assign = vi.spyOn(db, "assignRecordCompletionTask").mockResolvedValue({ id: 31, patientRecordId: 7, assignedToUserId: 22, assignedByAdminId: 14, status: "assigned", createdAt: new Date(), acceptedAt: null, completedAt: null, updatedAt: new Date() } as any);
    const notify = vi.spyOn(notifications, "notifyOwner").mockResolvedValue(true);
    try {
      await expect(appRouter.createCaller(context("user", "approved")).completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).rejects.toMatchObject({ code: "FORBIDDEN" });
      await expect(appRouter.createCaller(context("admin", "pending")).completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).rejects.toMatchObject({ code: "FORBIDDEN" });
      const removedAdmin = { ...context("admin", "approved"), user: { ...context("admin", "approved").user!, removedAt: new Date() } };
      await expect(appRouter.createCaller(removedAdmin).completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).rejects.toMatchObject({ code: "FORBIDDEN" });
      await expect(appRouter.createCaller(context("admin", "approved")).completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).resolves.toMatchObject({ id: 31, status: "assigned" });
      expect(assign).toHaveBeenCalledWith(7, 22, 14);
      expect(notify).toHaveBeenCalledWith(expect.objectContaining({ title: "Registry task assigned", content: expect.stringContaining("No patient, record, or clinical information") }));
      expect(notify.mock.calls[0][0].content).not.toMatch(/MUNR|patientRecordId|researchId/i);
    } finally { state.mockRestore(); assign.mockRestore(); notify.mockRestore(); }
  });
  it("rejects a non-approved task recipient and reports reassignment with generic operational wording", async () => {
    const state = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 22, openId: "pending-member", role: "user", accessStatus: "pending", removedAt: null });
    const assign = vi.spyOn(db, "assignRecordCompletionTask").mockResolvedValue({ id: 33, patientRecordId: 7, assignedToUserId: 22, assignedByAdminId: 14, status: "reassigned", createdAt: new Date(), acceptedAt: null, completedAt: null, updatedAt: new Date() } as any);
    const notify = vi.spyOn(notifications, "notifyOwner").mockResolvedValue(true);
    try {
      const caller = appRouter.createCaller(context("admin", "approved"));
      await expect(caller.completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).rejects.toMatchObject({ code: "BAD_REQUEST" });
      expect(assign).not.toHaveBeenCalled();
      state.mockResolvedValueOnce({ id: 22, openId: "approved-member", role: "user", accessStatus: "approved", removedAt: null });
      await expect(caller.completionTasks.assign({ patientRecordId: 7, assignedToUserId: 22 })).resolves.toMatchObject({ status: "reassigned" });
      expect(notify).toHaveBeenCalledWith(expect.objectContaining({ title: "Registry task reassigned", content: expect.not.stringMatching(/MUNR|research ID|diagnosis|cohort/i) }));
    } finally { state.mockRestore(); assign.mockRestore(); notify.mockRestore(); }
  });
  it("enforces assigned-member ownership and valid task-status order before accepting or completing", () => {
    expect(db.getTaskTransitionError("assigned", 22, 23, "accepted")).toBe("Only the assigned approved member can change this task.");
    expect(db.getTaskTransitionError("completed", 22, 22, "accepted")).toBe("Only an assigned task can be accepted.");
    expect(db.getTaskTransitionError("assigned", 22, 22, "completed")).toBe("Accept the task before marking it complete.");
    expect(db.getTaskTransitionError("reassigned", 22, 22, "accepted")).toBeNull();
    expect(db.getTaskTransitionError("accepted", 22, 22, "completed")).toBeNull();
  });
  it("alerts the owner with fixed generic text when a protected record completion status changes", async () => {
    const previous = vi.spyOn(db, "getPatientRecord").mockResolvedValue({ id: 7, completenessStatus: "incomplete" } as any);
    const update = vi.spyOn(db, "updatePatientRecord").mockResolvedValue({ id: 7, completenessStatus: "complete" } as any);
    const notify = vi.spyOn(notifications, "notifyOwner").mockResolvedValue(true);
    try {
      const input = { ...base, id: 7, researchId: newResearchId, cohort: "stroke" as const, clinicalData: stroke, missingItems: [], dataQualityStatus: "complete" as const, completenessStatus: "complete" as const };
      await expect(appRouter.createCaller(context("user", "approved")).registry.update(input)).resolves.toMatchObject({ completenessStatus: "complete" });
      expect(notify).toHaveBeenCalledWith({ title: "Registry completion status changed", content: "A protected record-completion status changed. No patient, record, or clinical information is included." });
      expect(notify.mock.calls[0][0].content).not.toMatch(/MUNR|research ID|diagnosis|cohort|email/i);
    } finally { previous.mockRestore(); update.mockRestore(); notify.mockRestore(); }
  });
  it("lets only the assigned approved member accept or complete a task through the protected task procedures", async () => {
    const accept = vi.spyOn(db, "acceptRecordCompletionTask").mockResolvedValue({ id: 31, status: "accepted" } as any);
    const complete = vi.spyOn(db, "completeRecordCompletionTask").mockResolvedValue({ id: 31, status: "completed" } as any);
    const notify = vi.spyOn(notifications, "notifyOwner").mockResolvedValue(true);
    try {
      const caller = appRouter.createCaller(context("user", "approved"));
      await expect(caller.completionTasks.accept({ taskId: 31 })).resolves.toMatchObject({ status: "accepted" });
      await expect(caller.completionTasks.complete({ taskId: 31 })).resolves.toMatchObject({ status: "completed" });
      expect(accept).toHaveBeenCalledWith(31, 14);
      expect(complete).toHaveBeenCalledWith(31, 14);
      expect(notify).toHaveBeenNthCalledWith(1, expect.objectContaining({ title: "Registry task accepted" }));
      expect(notify).toHaveBeenNthCalledWith(2, expect.objectContaining({ title: "Registry task completed" }));
    } finally { accept.mockRestore(); complete.mockRestore(); notify.mockRestore(); }
  });
  it("preserves a task event when the immediate owner alert cannot be delivered", async () => {
    const state = vi.spyOn(db, "getUserAdministrationState").mockResolvedValue({ id: 22, openId: "approved-member", role: "user", accessStatus: "approved", removedAt: null });
    const assign = vi.spyOn(db, "assignRecordCompletionTask").mockResolvedValue({ id: 32, patientRecordId: 8, assignedToUserId: 22, assignedByAdminId: 14, status: "assigned", createdAt: new Date(), acceptedAt: null, completedAt: null, updatedAt: new Date() } as any);
    const notify = vi.spyOn(notifications, "notifyOwner").mockRejectedValue(new Error("delivery unavailable"));
    try {
      await expect(appRouter.createCaller(context("admin", "approved")).completionTasks.assign({ patientRecordId: 8, assignedToUserId: 22 })).resolves.toMatchObject({ id: 32 });
      expect(assign).toHaveBeenCalledOnce();
    } finally { state.mockRestore(); assign.mockRestore(); notify.mockRestore(); }
  });
});
