import { z } from "zod";
import type { CohortClinicalData, PatientRecord, RadiologicalInvestigation } from "../drizzle/schema";

export const cohortSchema = z.enum(["stroke", "multiple_sclerosis", "abnormal_movements", "guillain_barre", "myasthenia_gravis", "myelopathy", "neuro_ophthalmology"]);
const choice = <T extends readonly [string, ...string[]]>(values: T) => z.enum(values);
const strokeClinicalSchema = z.object({ cohort: z.literal("stroke"), strokeType: choice(["ischemic", "hemorrhagic", "tia", "other", "unknown"]), vascularTerritory: choice(["anterior", "posterior", "multiple", "unknown"]), reperfusionTherapy: choice(["none", "iv_thrombolysis", "mechanical_thrombectomy", "both", "unknown"]), toastEtiology: choice(["large_artery", "cardioembolic", "small_vessel", "other_determined", "undetermined", "unknown"]) });
const multipleSclerosisClinicalSchema = z.object({ cohort: z.literal("multiple_sclerosis"), diseaseCourse: choice(["relapsing_remitting", "primary_progressive", "secondary_progressive", "clinically_isolated_syndrome", "unknown"]), disabilityLevel: choice(["mild", "moderate", "severe", "unknown"]), relapseActivity: choice(["active", "inactive", "unknown"]), diseaseModifyingTherapy: choice(["yes", "no", "unknown"]) });
const movementClinicalSchema = z.object({ cohort: z.literal("abnormal_movements"), movementPhenotype: choice(["tremor", "dystonia", "chorea", "ataxia", "tics", "other", "unknown"]), distribution: choice(["focal", "segmental", "generalized", "unknown"]), severity: choice(["mild", "moderate", "severe", "unknown"]), functionalImpact: choice(["none", "mild", "moderate", "severe", "unknown"]), treatmentResponse: choice(["responsive", "partially_responsive", "refractory", "unknown"]) });
const guillainBarreClinicalSchema = z.object({ cohort: z.literal("guillain_barre"), variant: choice(["aidp", "aman", "amsan", "miller_fisher", "other", "unknown"]), disabilityScore: choice(["0", "1", "2", "3", "4", "5", "6", "unknown"]), ventilatorySupport: choice(["none", "non_invasive", "invasive", "unknown"]), treatment: choice(["ivig", "plasmapheresis", "both", "supportive", "unknown"]) });
const myastheniaGravisClinicalSchema = z.object({ cohort: z.literal("myasthenia_gravis"), mgfaClass: choice(["I", "II", "III", "IV", "V", "unknown"]), antibodyStatus: choice(["achr", "musk", "lrp4", "seronegative", "unknown"]), thymomaStatus: choice(["present", "absent", "not_assessed", "unknown"]), crisisHistory: choice(["never", "past", "current", "unknown"]), treatmentResponse: choice(["responsive", "partially_responsive", "refractory", "unknown"]) });
const myelopathyClinicalSchema = z.object({ cohort: z.literal("myelopathy"), level: choice(["cervical", "thoracic", "lumbar", "multilevel", "unknown"]), cause: choice(["degenerative", "inflammatory", "compressive", "vascular", "infectious", "other", "unknown"]), upperMotorNeuronSigns: choice(["present", "absent", "unknown"]), lowerMotorNeuronFeatures: choice(["present", "absent", "unknown"]), bladderInvolvement: choice(["yes", "no", "unknown"]) });
const neuroOphthalmologyClinicalSchema = z.object({ cohort: z.literal("neuro_ophthalmology"), visualSyndrome: choice(["optic_neuritis", "visual_field_defect", "diplopia", "papilledema", "other", "unknown"]), laterality: choice(["right", "left", "bilateral", "unknown"]), acuityChange: choice(["improved", "stable", "worsened", "unknown"]), afferentDefect: choice(["yes", "no", "unknown"]), specialistAssessment: choice(["confirmed", "probable", "not_confirmed", "unknown"]) });
export const clinicalDataSchema = z.discriminatedUnion("cohort", [strokeClinicalSchema, multipleSclerosisClinicalSchema, movementClinicalSchema, guillainBarreClinicalSchema, myastheniaGravisClinicalSchema, myelopathyClinicalSchema, neuroOphthalmologyClinicalSchema]);

export const radiologicalInvestigationSchema = z.object({ modality: choice(["mri", "ct", "cta", "mra", "dsa", "doppler", "pet", "spect", "xray", "other"]), bodyRegion: choice(["brain", "spine", "cranial_nerves", "cerebral_vessels", "other"]), keyFinding: z.string().trim().min(2).max(500), lesionStatus: choice(["present", "absent", "indeterminate", "not_applicable"]), reportReference: z.string().trim().regex(/^RAD-[A-Z0-9-]{3,24}$/, "Use a non-identifying reference such as RAD-2026-001.").nullable().optional() });
const radiologyListSchema = z.array(radiologicalInvestigationSchema).max(20);
export const laboratoryInvestigationSchema = z.object({ testName: choice(["thyroid_function", "uric_acid", "ck", "b12_folate", "glucose_hba1c", "electrolytes", "inflammatory_markers", "autoimmune_panel", "other"]), resultStatus: choice(["normal", "abnormal", "borderline", "not_done", "unknown"]), resultSummary: z.string().trim().max(300).nullable().optional() });
export const neurologicalInvestigationSchema = z.object({ testName: choice(["emg_ncs", "csf_analysis", "fundus_examination", "eeg", "evoked_potentials", "genetic_testing", "cognitive_assessment", "other"]), resultStatus: choice(["normal", "abnormal", "borderline", "not_done", "unknown"]), resultSummary: z.string().trim().max(300).nullable().optional(), lowerMotorNeuronRelevant: z.boolean().optional() });
export const patientFollowUpSchema = z.object({ visitType: choice(["baseline", "routine", "post_discharge", "emergency", "telemedicine", "other"]), followUpStatus: choice(["completed", "scheduled", "missed", "lost_to_follow_up", "withdrawn"]), outcome: choice(["improved", "stable", "worsened", "recurrence", "deceased", "unknown"]), assessmentSummary: z.string().trim().min(2).max(500), nextFollowUpPlan: z.string().trim().max(300).nullable().optional(), timepoint: choice(["baseline", "1_month", "3_months", "6_months", "12_months", "annual", "unscheduled"]) });
const allowedUploadMimeTypes = ["application/pdf", "application/dicom", "image/jpeg", "image/png", "image/webp", "image/tiff", "text/plain"] as const;
export const researchFileInputSchema = z.object({ patientRecordId: z.number().int().positive(), fileName: z.string().trim().regex(/^(EGR|RAD|LAB|NEURO)-[A-Z0-9._-]{3,80}$/i, "Use a non-identifying filename such as RAD-2026-001.pdf."), mimeType: z.enum(allowedUploadMimeTypes), sizeBytes: z.number().int().positive().max(15 * 1024 * 1024), category: z.enum(["radiology_image", "radiology_report", "laboratory_report", "other"]), contentBase64: z.string().min(8).max(21 * 1024 * 1024).regex(/^[A-Za-z0-9+/]+={0,2}$/, "The file payload is not valid base64.") }).superRefine((value, context) => { if (/(patient|name|mrn|national|phone|mobile|dob|address)/i.test(value.fileName)) context.addIssue({ code: "custom", path: ["fileName"], message: "Filenames must not contain direct identifiers." }); });

export const patientInputSchema = z.object({ researchId: z.string().trim().toUpperCase().regex(/^EGR-[A-Z0-9]{4,16}$/, "Use the format EGR-XXXX."), cohort: cohortSchema, sex: z.enum(["female", "male", "intersex", "not_recorded"]), ageAtEnrollment: z.number().int().min(0).max(120), ageAtOnset: z.number().int().min(0).max(120).nullable().optional(), consentStatus: z.enum(["consented", "pending", "declined", "withdrawn"]), enrollmentStatus: z.enum(["screened", "enrolled", "completed", "withdrawn", "ineligible"]), clinicalStatus: z.enum(["active", "follow_up", "completed", "deceased", "unknown"]), primaryDiagnosis: z.string().trim().min(2).max(160), dataQualityStatus: z.enum(["draft", "complete", "query"]), clinicalData: clinicalDataSchema, radiologicalInvestigations: radiologyListSchema, laboratoryInvestigations: z.array(laboratoryInvestigationSchema).max(40), neurologicalInvestigations: z.array(neurologicalInvestigationSchema).max(40), followUpVisits: z.array(patientFollowUpSchema).max(50) }).superRefine((value, context) => { if (value.cohort !== value.clinicalData.cohort) context.addIssue({ code: "custom", path: ["clinicalData", "cohort"], message: "Clinical data must match the selected cohort." }); if (value.ageAtOnset !== null && value.ageAtOnset !== undefined && value.ageAtOnset > value.ageAtEnrollment) context.addIssue({ code: "custom", path: ["ageAtOnset"], message: "Age at onset cannot exceed age at enrolment." }); });
export const patientUpdateSchema = patientInputSchema.safeExtend({ id: z.number().int().positive() });
export const registryFiltersSchema = z.object({ cohort: cohortSchema.optional(), consentStatus: z.enum(["consented", "pending", "declined", "withdrawn"]).optional(), enrollmentStatus: z.enum(["screened", "enrolled", "completed", "withdrawn", "ineligible"]).optional(), clinicalStatus: z.enum(["active", "follow_up", "completed", "deceased", "unknown"]).optional(), dataQualityStatus: z.enum(["draft", "complete", "query"]).optional(), search: z.string().trim().max(24).optional(), ageMin: z.number().int().min(0).max(120).optional(), ageMax: z.number().int().min(0).max(120).optional() }).optional();
export function toAgeBand(age: number): string { if (age < 18) return "0-17"; if (age < 30) return "18-29"; if (age < 40) return "30-39"; if (age < 50) return "40-49"; if (age < 60) return "50-59"; if (age < 70) return "60-69"; if (age < 80) return "70-79"; return "80+"; }
function cleanValue(value: string | number | boolean | null | undefined) { return value ?? null; }
export function getPatientUpdateAuditSummary(input: { radiologicalInvestigations?: unknown[]; laboratoryInvestigations?: unknown[]; neurologicalInvestigations?: unknown[]; followUpVisits?: unknown[] }) { const sections: string[] = ["Core record"]; if (input.radiologicalInvestigations?.length) sections.push("radiological investigations"); if (input.laboratoryInvestigations?.length) sections.push("laboratory investigations"); if (input.neurologicalInvestigations?.length) sections.push("neurological investigations"); if (input.followUpVisits?.length) sections.push("patient follow-up"); return `${sections.join(", ")} updated`; }

export function toDeidentifiedExportRow(record: PatientRecord) { const clinicalData = record.clinicalData as CohortClinicalData; const base = { research_id: record.researchId, cohort: record.cohort, age_band_at_enrollment: toAgeBand(record.ageAtEnrollment), age_band_at_onset: record.ageAtOnset === null ? null : toAgeBand(record.ageAtOnset), consent_status: record.consentStatus, enrollment_status: record.enrollmentStatus, clinical_status: record.clinicalStatus, primary_diagnosis: record.primaryDiagnosis, data_quality_status: record.dataQualityStatus, radiological_investigations: (record.radiologicalInvestigations ?? []).map((item: RadiologicalInvestigation) => ({ modality: item.modality, body_region: item.bodyRegion, key_finding: item.keyFinding, lesion_status: item.lesionStatus })), laboratory_investigations: record.laboratoryInvestigations ?? [], neurological_investigations: record.neurologicalInvestigations ?? [], follow_up_visits: record.followUpVisits ?? [] };
  switch (clinicalData.cohort) {
    case "stroke": return { ...base, stroke_type: clinicalData.strokeType, vascular_territory: clinicalData.vascularTerritory, reperfusion_therapy: clinicalData.reperfusionTherapy, toast_etiology: clinicalData.toastEtiology };
    case "multiple_sclerosis": return { ...base, disease_course: clinicalData.diseaseCourse, disability_level: clinicalData.disabilityLevel, relapse_activity: clinicalData.relapseActivity, disease_modifying_therapy: clinicalData.diseaseModifyingTherapy };
    case "abnormal_movements": return { ...base, movement_phenotype: clinicalData.movementPhenotype, movement_distribution: clinicalData.distribution, movement_severity: clinicalData.severity, functional_impact: clinicalData.functionalImpact, treatment_response: clinicalData.treatmentResponse };
    case "guillain_barre": return { ...base, gbs_variant: clinicalData.variant, gbs_disability_score: clinicalData.disabilityScore, ventilatory_support: clinicalData.ventilatorySupport, treatment: clinicalData.treatment };
    case "myasthenia_gravis": return { ...base, mgfa_class: clinicalData.mgfaClass, antibody_status: clinicalData.antibodyStatus, thymoma_status: clinicalData.thymomaStatus, crisis_history: clinicalData.crisisHistory, treatment_response: clinicalData.treatmentResponse };
    case "myelopathy": return { ...base, myelopathy_level: clinicalData.level, myelopathy_cause: clinicalData.cause, upper_motor_neuron_signs: clinicalData.upperMotorNeuronSigns, lower_motor_neuron_features: clinicalData.lowerMotorNeuronFeatures, bladder_involvement: clinicalData.bladderInvolvement };
    case "neuro_ophthalmology": return { ...base, visual_syndrome: clinicalData.visualSyndrome, laterality: clinicalData.laterality, acuity_change: clinicalData.acuityChange, afferent_defect: clinicalData.afferentDefect, specialist_assessment: clinicalData.specialistAssessment };
  }
}
