import { describe, expect, it, vi } from "vitest";
import type { PatientRecord } from "../drizzle/schema";
import type { TrpcContext } from "./_core/context";
import { getInvestigationCoverage, getPatientUpdateAuditSummary, patientInputSchema, researchFileInputSchema, toDeidentifiedExportRow } from "./registry";
import { appRouter } from "./routers";
import * as db from "./db";
import { updatePatientRecordWithDb } from "./db";

function context(role: "admin" | "user", accessStatus: "pending" | "approved" | "suspended"): TrpcContext { return { user: { id: 14, openId: "test-user", name: "Test User", email: "test@example.com", loginMethod: "manus", role, accessStatus, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] }; }
const base = { sex: "not_recorded", ageAtEnrollment: 50, ageAtOnset: 48, consentStatus: "consented", enrollmentStatus: "enrolled", clinicalStatus: "active", primaryDiagnosis: "Research diagnosis", dataQualityStatus: "draft", completenessStatus: "incomplete", missingItems: ["follow_up"], completionOwnerUserId: null, briefClinicalHistory: null, positiveExaminationFindings: null, dischargeTreatment: null, immuneTherapies: [], msDoseAdherence: [], radiologicalInvestigations: [], laboratoryInvestigations: [], neurologicalInvestigations: [], protocolInvestigations: [], followUpVisits: [] } as const;
const stroke = { cohort: "stroke", strokeType: "ischemic", vascularTerritory: "mca_complete", reperfusionTherapy: "none", toastEtiology: "unknown", majorComplication: "none", strokeEvaluation: "nihss_and_mrs" } as const;
const ms = { cohort: "multiple_sclerosis", diseaseCourse: "relapsing_remitting", disabilityLevel: "mild", relapseActivity: "inactive", diseaseModifyingTherapy: "ocrelizumab", msfcAssessed: "yes", timed25FootWalkSeconds: 10, nineHolePegTestSeconds: 24, pasat3Score: 42, tuberculinScreen: "negative", chestTuberculosisScreen: "clear", msEvaluation: "clinical_mri_msfc" } as const;
const cidp = { cohort: "cidp", variant: "madsam", diagnosticPathway: "vasculitic_neuropathy", disabilityLevel: "moderate", emgNcsEvidence: "axonal_multifocal", csfProteinStatus: "elevated", cidpEvaluation: "vasculitis_workup" } as const;

describe("Mansoura University registry validation", () => {
  it("requires a pseudonymised MUNR Research ID and rejects direct identifiers", () => { expect(patientInputSchema.shape.researchId.safeParse("MUNR-2026A").success).toBe(true); expect(patientInputSchema.shape.researchId.safeParse("EGR-2026A").success).toBe(false); expect(patientInputSchema.shape.researchId.safeParse("AHMED-MRN-12345").success).toBe(false); });
  it("accepts all approved neurology cohorts including CIDP", () => {
    const cases = [
      ["stroke", stroke], ["ms", ms], ["movement", { cohort: "abnormal_movements", movementPhenotype: "tremor", distribution: "focal", severity: "mild", functionalImpact: "mild", treatmentResponse: "responsive", movementEvaluation: "phenomenology_only" }], ["gbs", { cohort: "guillain_barre", variant: "aidp", disabilityScore: "2", ventilatorySupport: "none", treatment: "ivig", gbsEvaluation: "gbs_disability_only" }], ["mg", { cohort: "myasthenia_gravis", mgfaClass: "II", antibodyStatus: "achr", thymomaStatus: "absent", crisisHistory: "never", treatmentResponse: "responsive", mgEvaluation: "mgfa_only" }], ["myelopathy", { cohort: "myelopathy", level: "cervical", cause: "compressive", upperMotorNeuronSigns: "present", lowerMotorNeuronFeatures: "absent", bladderInvolvement: "no", myelopathyEvaluation: "mri_and_neuroexam" }], ["neurooph", { cohort: "neuro_ophthalmology", visualSyndrome: "optic_neuritis", laterality: "right", acuityChange: "stable", afferentDefect: "yes", diseaseClassification: "nmosd", antibodyProfile: "aqp4_positive", linkedSystemicDisease: "none", neuroOphEvaluation: "antibody_workup" }], ["cidp", cidp],
    ] as const;
    for (const [suffix, clinicalData] of cases) expect(patientInputSchema.safeParse({ ...base, researchId: `MUNR-${suffix.toUpperCase()}26`, cohort: clinicalData.cohort, clinicalData }).success, suffix).toBe(true);
  });
  it("captures stroke complications, MS pre-immunosuppression screening and dated dose adherence", () => {
    const parsed = patientInputSchema.safeParse({ ...base, researchId: "MUNR-MSADHERE26", cohort: "multiple_sclerosis", clinicalData: { ...ms, relapseActivity: "active" }, immuneTherapies: [{ therapyClass: "b_cell_depleting", agent: "Ocrelizumab", status: "active", startDate: "2026-08-01", infectionExclusionStatus: "cleared", infectionExclusionNote: "Protocol review documented" }], msDoseAdherence: [{ therapyName: "Ocrelizumab", doseDate: "2026-08-01", doseStatus: "taken" }], protocolInvestigations: [{ itemCode: "infection_exclusion_pre_immunotherapy", status: "completed" }] });
    expect(parsed.success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-SCREEN26", cohort: "multiple_sclerosis", clinicalData: ms, radiologicalInvestigations: [{ modality: "xray", bodyRegion: "chest", keyFinding: "Screening review", lesionStatus: "not_applicable" }], laboratoryInvestigations: [{ testName: "varicella_immunity", resultStatus: "normal" }], protocolInvestigations: [{ itemCode: "chest_imaging_pre_immunotherapy", status: "completed" }, { itemCode: "tuberculin_tb_screen_pre_immunotherapy", status: "completed" }, { itemCode: "varicella_immunity_pre_immunotherapy", status: "completed" }] }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-STROKE26", cohort: "stroke", clinicalData: { ...stroke, vascularTerritory: "vertebrobasilar", majorComplication: "aspiration_pneumonia" } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-NOTMS26", cohort: "stroke", clinicalData: stroke, msDoseAdherence: [{ therapyName: "Interferon", doseDate: "2026-08-01", doseStatus: "missed" }] }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-BADINF26", cohort: "multiple_sclerosis", clinicalData: ms, immuneTherapies: [{ therapyClass: "biologic", status: "planned", infectionExclusionStatus: "invalid" }] }).success).toBe(false);
  });
  it("records only the explicit evaluation items relevant to the selected cohort", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-EVALSTR26", cohort: "stroke", clinicalData: { ...stroke, evaluationItems: [{ code: "stroke_nihss", label: "Stroke NIHSS", status: "recorded", value: "12" }, { code: "stroke_mrs", label: "Stroke modified Rankin Scale (mRS)", status: "recorded", value: "3" }] } }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-EVALBAD26", cohort: "stroke", clinicalData: { ...stroke, evaluationItems: [{ code: "ms_edss", label: "MS EDSS disability", status: "recorded", value: "3.5" }] } }).success).toBe(false);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-EVALCID26", cohort: "cidp", clinicalData: { ...cidp, evaluationItems: [{ code: "cidp_variant_pattern", label: "CIDP variant pattern", status: "recorded", value: "MADSAM" }, { code: "cidp_incat_onls", label: "CIDP INCAT / ONLS disability", status: "recorded", value: "5" }, { code: "cidp_vasculitic_features", label: "CIDP vasculitic features", status: "not_assessed" }] } }).success).toBe(true);
  });
  it("captures NMOSD, MOGAD, GCA, mononeuritis multiplex, and vasculitic-neuropathy pathways", () => {
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-GCA26", cohort: "neuro_ophthalmology", clinicalData: { cohort: "neuro_ophthalmology", visualSyndrome: "optic_neuritis", laterality: "left", acuityChange: "worsened", afferentDefect: "yes", diseaseClassification: "giant_cell_arteritis", antibodyProfile: "not_done", linkedSystemicDisease: "systemic_vasculitis", neuroOphEvaluation: "gca_pathway" }, immuneTherapies: [{ therapyClass: "corticosteroid", status: "active" }] }).success).toBe(true);
    expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-VASC26", cohort: "cidp", clinicalData: { ...cidp, diagnosticPathway: "mononeuritis_multiplex" }, neurologicalInvestigations: [{ testName: "nerve_biopsy", resultStatus: "abnormal" }] }).success).toBe(true);
  });
  it("enforces completion workflow consistency", () => { expect(patientInputSchema.safeParse({ ...base, researchId: "MUNR-COMP26", cohort: "cidp", completenessStatus: "complete", missingItems: ["laboratory"], clinicalData: cidp }).success).toBe(false); });
  it("summarises radiology, laboratory, neurological, and protocol investigation coverage for the overview", () => { const coverage = getInvestigationCoverage([{ radiologicalInvestigations: [{}], laboratoryInvestigations: [{}], neurologicalInvestigations: [{}], protocolInvestigations: [{ status: "completed" }, { status: "not_indicated" }] }, { radiologicalInvestigations: [], laboratoryInvestigations: [{}], neurologicalInvestigations: [], protocolInvestigations: [{ status: "ordered" }] }]); expect(coverage).toEqual({ totalRecords: 2, radiologyRecorded: 1, laboratoryRecorded: 2, neurologicalRecorded: 1, protocolChecklistComplete: 1, protocolChecklistOutstanding: 1 }); });
  it("exports research-safe summaries while excluding clinical narratives, adherence dates, completion ownership, and research files", () => {
    const row = toDeidentifiedExportRow({ id: 7, researchId: "MUNR-STROKE26", cohort: "stroke", sex: "male", ageAtEnrollment: 64, ageAtOnset: 63, consentStatus: "consented", enrollmentStatus: "enrolled", clinicalStatus: "active", dataQualityStatus: "complete", completenessStatus: "incomplete", missingItems: ["follow_up"], completionOwnerUserId: 33, primaryDiagnosis: "Ischaemic stroke", briefClinicalHistory: "Sensitive narrative", positiveExaminationFindings: "Sensitive findings", dischargeTreatment: "Sensitive plan", immuneTherapies: [{ therapyClass: "corticosteroid", status: "completed", agent: "Prednisone", startDate: "2026-01-01" }], msDoseAdherence: [], clinicalData: stroke, radiologicalInvestigations: [{ modality: "mri", bodyRegion: "brain", keyFinding: "Focal lesion", lesionStatus: "present", reportReference: "RAD-2026-001" }], laboratoryInvestigations: [{ testName: "hba1c", resultStatus: "abnormal", resultSummary: "Above local reference range" }], neurologicalInvestigations: [{ testName: "fundus_examination", resultStatus: "normal" }], protocolInvestigations: [{ itemCode: "vascular_imaging", status: "completed" }], followUpVisits: [{ visitType: "routine", followUpStatus: "completed", outcome: "stable", assessmentSummary: "Stable", timepoint: "3_months" }], researchFiles: [{ fileName: "RAD-2026-001.pdf", storageKey: "key", url: "url", mimeType: "application/pdf", sizeBytes: 4, category: "radiology_report", uploadedAt: "2026-01-01", uploadedByUserId: 14 }], createdByUserId: 1, lastModifiedByUserId: 2, createdAt: new Date(), updatedAt: new Date() } as PatientRecord);
    expect(row).toMatchObject({ research_id: "MUNR-STROKE26", age_band_at_enrollment: "60-69", vascular_territory: "mca_complete", major_complication: "none", completeness_status: "incomplete" }); expect(row).not.toHaveProperty("completionOwnerUserId"); expect(row).not.toHaveProperty("research_files"); expect(row).not.toHaveProperty("briefClinicalHistory"); expect(row).not.toHaveProperty("msDoseAdherence"); expect(row.immune_therapies).toEqual([{ therapy_class: "corticosteroid", agent: "Prednisone", status: "completed" }]); expect(row.cohort_evaluation_statuses).toEqual([]);
  });
  it("protects upload metadata and enforces allowed file types and size", () => { expect(researchFileInputSchema.safeParse({ patientRecordId: 1, fileName: "RAD-2026-001.pdf", mimeType: "application/pdf", sizeBytes: 1024, category: "radiology_report", contentBase64: "YWJjZA==" }).success).toBe(true); expect(researchFileInputSchema.safeParse({ patientRecordId: 1, fileName: "patient-name.pdf", mimeType: "application/pdf", sizeBytes: 1024, category: "radiology_report", contentBase64: "YWJjZA==" }).success).toBe(false); });
  it("writes an audit event that identifies histories, immune therapy, adherence, discharge treatment and follow-up changes", async () => { const auditRows: unknown[] = []; let selected = 0; const fakeDb: any = { select: () => ({ from: () => ({ where: () => ({ limit: async () => { selected += 1; return selected === 1 ? [{ id: 7 }] : [{ id: 7, researchId: "MUNR-FOLLOW26" }]; } }) }) }), update: () => ({ set: () => ({ where: async () => undefined }) }), insert: () => ({ values: async (row: unknown) => auditRows.push(row) }) }; const input: any = { ...base, researchId: "MUNR-FOLLOW26", cohort: "multiple_sclerosis", briefClinicalHistory: "History", positiveExaminationFindings: "Findings", dischargeTreatment: "Treatment", immuneTherapies: [{ therapyClass: "ivig", status: "active" }], msDoseAdherence: [{ therapyName: "DMT", doseDate: "2026-08-01", doseStatus: "taken" }], clinicalData: ms, followUpVisits: [{ visitType: "routine", followUpStatus: "completed", outcome: "stable", assessmentSummary: "Stable", timepoint: "3_months" }] }; await updatePatientRecordWithDb(fakeDb, 7, input, 14); expect(auditRows).toHaveLength(1); expect(auditRows[0]).toMatchObject({ patientRecordId: 7, actorUserId: 14, action: "updated" }); expect(getPatientUpdateAuditSummary(input)).toContain("immune therapy"); });
  it("blocks pending users and permits an approved administrator to approve a new user", async () => { await expect(appRouter.createCaller(context("user", "pending")).registry.overview()).rejects.toMatchObject({ code: "FORBIDDEN" }); const setAccess = vi.spyOn(db, "setUserAccessStatus").mockResolvedValue(undefined); const logAccess = vi.spyOn(db, "logAccessChange").mockResolvedValue(undefined); try { await expect(appRouter.createCaller(context("admin", "approved")).administration.setAccess({ userId: 27, accessStatus: "approved" })).resolves.toEqual({ success: true }); expect(setAccess).toHaveBeenCalledWith(27, "approved"); } finally { setAccess.mockRestore(); logAccess.mockRestore(); } });
  it("permits messages only for approved users and rejects self-messages and patient-data references", async () => { const recipients = vi.spyOn(db, "listApprovedMessageRecipients").mockResolvedValue([{ id: 22, name: "Approved Colleague", email: "colleague@example.edu", role: "user" }]); const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(true); const send = vi.spyOn(db, "sendDirectMessage").mockResolvedValue({ id: 1, senderUserId: 14, recipientUserId: 22, body: "Please review the protocol checklist.", createdAt: new Date() }); try { await expect(appRouter.createCaller(context("user", "pending")).messages.recipients()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("user", "approved")).messages.recipients()).resolves.toHaveLength(1); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 14, body: "Self message" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 22, body: "Please open MUNR-ABC1234" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(appRouter.createCaller(context("user", "approved")).messages.send({ recipientUserId: 22, body: "Please review the protocol checklist." })).resolves.toMatchObject({ recipientUserId: 22 }); expect(recipients).toHaveBeenCalledWith(14); expect(send).toHaveBeenCalledWith(14, 22, "Please review the protocol checklist."); } finally { recipients.mockRestore(); recipientIsApproved.mockRestore(); send.mockRestore(); } });
  it("blocks message content containing patient-name, phone-number, or national-ID references and rejects unapproved recipients", async () => { const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(true); const send = vi.spyOn(db, "sendDirectMessage").mockResolvedValue({ id: 2, senderUserId: 14, recipientUserId: 22, body: "Protocol meeting at 10:00.", createdAt: new Date() }); try { const caller = appRouter.createCaller(context("user", "approved")); await expect(caller.messages.send({ recipientUserId: 22, body: "Patient name is withheld" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(caller.messages.send({ recipientUserId: 22, body: "Use the patient phone number" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(caller.messages.send({ recipientUserId: 22, body: "National ID review" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); recipientIsApproved.mockResolvedValue(false); await expect(caller.messages.send({ recipientUserId: 22, body: "Protocol meeting at 10:00." })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(send).not.toHaveBeenCalled(); } finally { recipientIsApproved.mockRestore(); send.mockRestore(); } });
  it("does not reveal a direct-message thread when the recipient is not approved", async () => { const recipientIsApproved = vi.spyOn(db, "isApprovedMessageRecipient").mockResolvedValue(false); const listThread = vi.spyOn(db, "listDirectMessages").mockResolvedValue([]); try { await expect(appRouter.createCaller(context("user", "approved")).messages.thread({ recipientUserId: 22 })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(listThread).not.toHaveBeenCalled(); } finally { recipientIsApproved.mockRestore(); listThread.mockRestore(); } });
});
