import fs from "node:fs";
const path = "/home/ubuntu/neuro-registry-egypt/client/src/pages/PatientEditor.tsx";
let text = fs.readFileSync(path, "utf8");
text = text.replace(/type Cohort = [^\n]+;/, 'type Cohort = "stroke" | "multiple_sclerosis" | "abnormal_movements" | "guillain_barre" | "myasthenia_gravis" | "myelopathy" | "neuro_ophthalmology";');
text = text.replace(/const cohortLabels: Record<Cohort, string> = \{[^\n]+\};/, 'const cohortLabels: Record<Cohort, string> = { stroke: "Stroke", multiple_sclerosis: "Multiple Sclerosis (MS)", abnormal_movements: "Abnormal Movements", guillain_barre: "Guillain–Barré Syndrome (GBS)", myasthenia_gravis: "Myasthenia Gravis (MG)", myelopathy: "Myelopathy", neuro_ophthalmology: "Neuro-ophthalmology" };');
const start = text.indexOf('const clinicalFields: Record<Cohort, ClinicalField[]> = {');
const end = text.indexOf('const emptyRadiology:', start);
const fields = `const clinicalFields: Record<Cohort, ClinicalField[]> = {
  stroke: [{ key: "strokeType", label: "Stroke type", choices: choices([["ischemic", "Ischaemic"], ["hemorrhagic", "Haemorrhagic"], ["tia", "TIA"], ["other", "Other"], ["unknown", "Unknown"]]) }, { key: "vascularTerritory", label: "Vascular territory", choices: choices([["anterior", "Anterior"], ["posterior", "Posterior"], ["multiple", "Multiple"], ["unknown", "Unknown"]]) }, { key: "reperfusionTherapy", label: "Reperfusion therapy", choices: choices([["none", "None"], ["iv_thrombolysis", "IV thrombolysis"], ["mechanical_thrombectomy", "Mechanical thrombectomy"], ["both", "Both"], ["unknown", "Unknown"]]) }, { key: "toastEtiology", label: "TOAST aetiology", choices: choices([["large_artery", "Large artery"], ["cardioembolic", "Cardioembolic"], ["small_vessel", "Small vessel"], ["other_determined", "Other determined"], ["undetermined", "Undetermined"], ["unknown", "Unknown"]]) }],
  multiple_sclerosis: [{ key: "diseaseCourse", label: "Disease course", choices: choices([["relapsing_remitting", "Relapsing–remitting"], ["primary_progressive", "Primary progressive"], ["secondary_progressive", "Secondary progressive"], ["clinically_isolated_syndrome", "Clinically isolated syndrome"], ["unknown", "Unknown"]]) }, { key: "disabilityLevel", label: "Disability level", choices: choices([["mild", "Mild"], ["moderate", "Moderate"], ["severe", "Severe"], ["unknown", "Unknown"]]) }, { key: "relapseActivity", label: "Relapse activity", choices: choices([["active", "Active"], ["inactive", "Inactive"], ["unknown", "Unknown"]]) }, { key: "diseaseModifyingTherapy", label: "Disease-modifying therapy", choices: choices([["yes", "Yes"], ["no", "No"], ["unknown", "Unknown"]]) }],
  abnormal_movements: [{ key: "movementPhenotype", label: "Movement phenotype", choices: choices([["tremor", "Tremor"], ["dystonia", "Dystonia"], ["chorea", "Chorea"], ["ataxia", "Ataxia"], ["tics", "Tics"], ["other", "Other"], ["unknown", "Unknown"]]) }, { key: "distribution", label: "Distribution", choices: choices([["focal", "Focal"], ["segmental", "Segmental"], ["generalized", "Generalised"], ["unknown", "Unknown"]]) }, { key: "severity", label: "Severity", choices: choices([["mild", "Mild"], ["moderate", "Moderate"], ["severe", "Severe"], ["unknown", "Unknown"]]) }, { key: "functionalImpact", label: "Functional impact", choices: choices([["none", "None"], ["mild", "Mild"], ["moderate", "Moderate"], ["severe", "Severe"], ["unknown", "Unknown"]]) }, { key: "treatmentResponse", label: "Treatment response", choices: choices([["responsive", "Responsive"], ["partially_responsive", "Partially responsive"], ["refractory", "Refractory"], ["unknown", "Unknown"]]) }],
  guillain_barre: [{ key: "variant", label: "GBS variant", choices: choices([["aidp", "AIDP"], ["aman", "AMAN"], ["amsan", "AMSAN"], ["miller_fisher", "Miller Fisher"], ["other", "Other"], ["unknown", "Unknown"]]) }, { key: "disabilityScore", label: "Disability score", choices: choices([["0", "0"], ["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["unknown", "Unknown"]]) }, { key: "ventilatorySupport", label: "Ventilatory support", choices: choices([["none", "None"], ["non_invasive", "Non-invasive"], ["invasive", "Invasive"], ["unknown", "Unknown"]]) }, { key: "treatment", label: "Treatment", choices: choices([["ivig", "IVIG"], ["plasmapheresis", "Plasmapheresis"], ["both", "Both"], ["supportive", "Supportive"], ["unknown", "Unknown"]]) }],
  myasthenia_gravis: [{ key: "mgfaClass", label: "MGFA class", choices: choices([["I", "Class I"], ["II", "Class II"], ["III", "Class III"], ["IV", "Class IV"], ["V", "Class V"], ["unknown", "Unknown"]]) }, { key: "antibodyStatus", label: "Antibody status", choices: choices([["achr", "AChR"], ["musk", "MuSK"], ["lrp4", "LRP4"], ["seronegative", "Seronegative"], ["unknown", "Unknown"]]) }, { key: "thymomaStatus", label: "Thymoma status", choices: choices([["present", "Present"], ["absent", "Absent"], ["not_assessed", "Not assessed"], ["unknown", "Unknown"]]) }, { key: "crisisHistory", label: "Crisis history", choices: choices([["never", "Never"], ["past", "Past"], ["current", "Current"], ["unknown", "Unknown"]]) }, { key: "treatmentResponse", label: "Treatment response", choices: choices([["responsive", "Responsive"], ["partially_responsive", "Partially responsive"], ["refractory", "Refractory"], ["unknown", "Unknown"]]) }],
  myelopathy: [{ key: "level", label: "Spinal level", choices: choices([["cervical", "Cervical"], ["thoracic", "Thoracic"], ["lumbar", "Lumbar"], ["multilevel", "Multilevel"], ["unknown", "Unknown"]]) }, { key: "cause", label: "Likely cause", choices: choices([["degenerative", "Degenerative"], ["inflammatory", "Inflammatory"], ["compressive", "Compressive"], ["vascular", "Vascular"], ["infectious", "Infectious"], ["other", "Other"], ["unknown", "Unknown"]]) }, { key: "upperMotorNeuronSigns", label: "Upper motor neuron signs", choices: choices([["present", "Present"], ["absent", "Absent"], ["unknown", "Unknown"]]) }, { key: "lowerMotorNeuronFeatures", label: "Lower motor neuron features", choices: choices([["present", "Present"], ["absent", "Absent"], ["unknown", "Unknown"]]) }, { key: "bladderInvolvement", label: "Bladder involvement", choices: choices([["yes", "Yes"], ["no", "No"], ["unknown", "Unknown"]]) }],
  neuro_ophthalmology: [{ key: "visualSyndrome", label: "Visual syndrome", choices: choices([["optic_neuritis", "Optic neuritis"], ["visual_field_defect", "Visual field defect"], ["diplopia", "Diplopia"], ["papilledema", "Papilledema"], ["other", "Other"], ["unknown", "Unknown"]]) }, { key: "laterality", label: "Laterality", choices: choices([["right", "Right"], ["left", "Left"], ["bilateral", "Bilateral"], ["unknown", "Unknown"]]) }, { key: "acuityChange", label: "Visual acuity change", choices: choices([["improved", "Improved"], ["stable", "Stable"], ["worsened", "Worsened"], ["unknown", "Unknown"]]) }, { key: "afferentDefect", label: "Afferent defect", choices: choices([["yes", "Yes"], ["no", "No"], ["unknown", "Unknown"]]) }, { key: "specialistAssessment", label: "Specialist assessment", choices: choices([["confirmed", "Confirmed"], ["probable", "Probable"], ["not_confirmed", "Not confirmed"], ["unknown", "Unknown"]]) }],
};
`;
if (start === -1 || end === -1) throw new Error("Clinical fields markers not found");
text = text.slice(0, start) + fields + text.slice(end);
fs.writeFileSync(path, text);
